spring.application.name=translog-batch
server.port=8080

# BASE DE DATOS MYSQL

spring.datasource.url=jdbc:mysql://mysql:3306/translog?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=translog

spring.datasource.password=translog123

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# SPRING BATCH

spring.batch.jdbc.initialize-schema=always

spring.batch.job.enabled=false

# SQL

spring.sql.init.mode=always

# LOGGING

logging.level.org.springframework.batch=INFO

logging.level.cl.translog.batch=INFO

# CONFIGURACIÓN DE LA APLICACIÓN

app.grid-size=4

app.pool-size=4

app.chunk-size=50

app.total-records=1000

app.output-file-cuentas-anuales=output/resumen_cuentas_anuales.csv

app.output-file-intereses=output/resumen_intereses.csv

app.output-file-transacciones=output/resumen_transacciones.csv
