spring.application.name=bff-cajero
server.port=8083
core-streaming.base-url=${CORE_STREAMING_BASE_URL:http://localhost:8080}

server.ssl.enabled=true
server.ssl.key-store=${SSL_KEYSTORE:classpath:keystore.p12}
server.ssl.key-store-password=${SSL_KEYSTORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bff-local

security.users.web.password=${WEB_PASSWORD:web123}
security.users.mobile.password=${MOBILE_PASSWORD:mobile123}
security.users.cajero.password=${CAJERO_PASSWORD:cajero123}

#Usuario cajero: cajerouser